name: emscripten CI

on:
  push:
    branches: [ master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ master ]

jobs:
  build-emscripten:
    runs-on: ubuntu-latest
    steps:
    - uses: mymindstorm/setup-emsdk@v14
      with:
        version: '3.1.56'
    - uses: actions/checkout@v4
    - name: verify
      run: emcc -v
    - name: configure
      run: emcmake cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
    - name: build
      run: cmake --build build
    - name: pack
      run: npm pack
    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        path: ldbdump-*.tgz
    - name: publish to npm
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      run: npm publish ldbdump-*.tgz
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
